### ISSUE TITLE
isLocatedIn clashes in Py loader

### ISSUE THREAD

**Issue by szarnyasg** [ftsrg/sigmod2014-pc#10]
Problem: `isLocatedIn` edges clash, causing the Python loader to fail.

Temporary workaround: rename edges to incorporate their source type.

```bash
$ ls -1 csvs/sf1k/*IsLocatedIn*
csvs/sf1k/comment_commentIsLocatedIn_place.csv
csvs/sf1k/organisation_organisationIsLocatedIn_place.csv
csvs/sf1k/person_personIsLocatedIn_place.csv
```

**Comment by attilanagy234** [comment]
This issue issue was resolved with the newer version of the loader. Closing.
