### ISSUE TITLE
Rename sf1k to p1k

### ISSUE THREAD

**Issue by szarnyasg** [ftsrg/sigmod2014-pc#12]
`p{1,10,...}k` are the correct names instead of `SFxx`.

There are not too many instances:
```bash
$ ag sf1k
utils.cpp
35:        params.ChangePath = getenv_string("ChangePath", "../../csvs/sf1k/");
36:        params.ParamsPath = getenv_string("ParamsPath", "../../params/sf1k/");

README.md
37:Put [converted CSVs](../README.md#preprocessing-the-provided-data-sets) to `../csvs/sf1k/` or set `$ChangePath` environmental variable.
51:Set `$ChangePath` environmental variable to the data set (default: `../../csvs/sf1k/`).
53:To generate query parameters, set `$ParamsPath` (default: `../../params/sf1k/`), then run:
```

**Comment by marci543** [comment]
It is intentional to distinguish original data set (`sf{1,10}k`) from the later generated ones (`p{1,10,...}k`). The former has example query parameters and answers for them which are used as tests. The default configuration expects the original data set and runs the tests.

**Comment by szarnyasg** [comment]
I see. It could stay this way or we could rename it to `o{1,10}k` for the original data sets. WDYT?

**Comment by marci543** [comment]
I checked and the test results do differ for the original and the generated data therefore we must keep them.

Clarifying the naming convention would be great.
Can you please rename these preprocessed .zip files and the folders inside them?
https://github.com/ftsrg/sigmod2014-pc#preprocessed-data-sets
