### ISSUE TITLE
Define and measure microbenchmarks

### ISSUE THREAD

**Issue by szarnyasg** [ftsrg/sigmod2014-pc#20]
E.g. for MSBFS variants.

Measure them.
Use the latest scripts despite the commit under measurement: `git checkout master -- scripts/`

**Comment by marci543** [comment]
- [Optimize finding top k elements](https://github.com/ftsrg/sigmod2014-pc/commit/afeea07785cd4479827474fca593d55abc992a15): `afeea07785cd4479827474fca593d55abc992a15` vs. `afeea07785cd4479827474fca593d55abc992a15~1`
- Dense relabelling

**Comment by szarnyasg** [comment]
Perfect, thanks
