### ISSUE TITLE
Benchmarking single-threaded execution

### ISSUE THREAD

**Issue by szarnyasg** [ftsrg/sigmod2014-pc#23]
Add option to script to pin the execution to a single thread.

**Comment by marci543** [comment]
It is possible to use the `ThreadsNum` environment variable, which is already implemented by the C++ code:
```bash
ThreadsNum=1 ./scripts/run.sh
```
```
...
Run query1: cpp/cmake-build-release/sigmod2014pc_cpp csvs/p1k/ PARAM 1 757 383 0
cpp,1,Threads: 1/4
q1,1250896,119027
...
```

**Comment by szarnyasg** [comment]
@marci543 sorry, the original post was unclear. I'd like to have an option to pin a benchmark to a single (logical) CPU core. This way, we can benchmark the single-threaded performance of existing solutions. See details in the 'threats to validity' section of the paper.
